---
apt_repos:
  - name: chrome
    key_url: "https://dl.google.com/linux/linux_signing_key.pub"
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  - name: vscode
    key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
apt_installed_packages:
  - code 
  - curl
  - git
  - google-chrome-stable
  - htop
  - stow
  - vim
  - wget
