---

# Dotfiles 

dotfiles_repo: ""

# APT 

apt_repos:
  - name: chrome
    key_url: "https://dl.google.com/linux/linux_signing_key.pub"
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  - name: vscode
    key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

apt_installed_packages:
  - code 
  - curl
  - git
  - google-chrome-stable
  - htop
  - python3-psutil
  - ripgrep
  - stow
  - vim
  - wget

# Gnome configuration

gnome_desktop_interface:
  - name: color-scheme
    value: "'prefer-dark'"
  - name: gtk-theme
    value: "'Yaru-sage-dark'"
  - name: icon-theme
    value: "'Yaru-sage'"

terminal_default_profile_id: f2201379-9c1f-4a5b-8ec6-0f8ba83ccfef 

terminal_configuration:
  - name: background-color
    value: "'rgb(0,0,0)'"
  - name: foreground-color
    value: "'rgb(170,170,170)'"
  - name: use-theme-colors
    value: "false"
  - name: visible-name
    value: "'default'"

path_to_backgroud: files/wallpaper.jpg
