---

# Dotfiles 

dotfiles_repo: ""

# APT 

apt_repos:
  - name: chrome
    key_url: "https://dl.google.com/linux/linux_signing_key.pub"
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  - name: vscode
    key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
  - name: vbox
    key_url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian jammy contrib"

apt_installed_packages:
  - code 
  - curl
  - dislocker
  - dkms
  - exfat-fuse
  - git
  - google-chrome-stable
  - htop
  - ntfs-3g
  - p7zip-full
  - pdftk
  - python3-psutil
  - ripgrep
  - solaar
  - stow
  - tmux
  - vim
  - virtualbox-7.0
  - vlc
  - wget

apt_deb_packages_urls:

  - "https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megasync-xUbuntu_22.04_amd64.deb" # MEGA
  - "https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-Ubuntu-22.04-amd64.deb" # Veracrypt
  - "https://zoom.us/client/latest/zoom_amd64.deb" # Zoom

# Gnome configuration

gnome_desktop_interface:
  - name: color-scheme
    value: "'prefer-dark'"
  - name: gtk-theme
    value: "'Yaru-sage-dark'"
  - name: icon-theme
    value: "'Yaru-sage'"

terminal_default_profile_id: f2201379-9c1f-4a5b-8ec6-0f8ba83ccfef 

terminal_configuration:
  - name: background-color
    value: "'rgb(0,0,0)'"
  - name: foreground-color
    value: "'rgb(170,170,170)'"
  - name: use-theme-colors
    value: "false"
  - name: visible-name
    value: "'default'"

path_to_backgroud: files/wallpaper.jpg

# Terminal configuration

fonts_urls:
  - "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/CommitMono.zip"
  - "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraMono.zip"
