---
- name: Set dark mode
  community.general.dconf:
    key: "/org/gnome/desktop/interface/{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_desktop_interface }}"

- name: Copy wallpaper to the Pictures directory
  ansible.builtin.copy:
    src: "files/wallpaper.jpg"
    dest: "{{ ansible_env.HOME }}/Pictures/wallpaper.jpg"

- name: Set desktop background
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file://{{ ansible_env.HOME }}/Pictures/wallpaper.jpg'"

- name: Keep Dock fixed (Auto-hide the dock)
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"
