---

- name: Ensure the Code directory exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Code"
    state: directory
    mode: "0700"

#- name: Checkout dotfiles repository
#  ansible.builtin.git:
#    repo: "git@github.com:{{ dotfiles_repo }}"
#    dest: "{{ ansible_env.HOME }}/Code/dotfiles"

- name: Find stow packages
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/Code/dotfiles"
    file_type: directory
    use_regex: yes
  register: stow_packages

- name: Create list of stow packages
  ansible.builtin.set_fact:
    "stow_pkgs" : "{{ stow_packages.files | map(attribute='path') | list  }}"

- name: Run stow
  ansible.builtin.command:
    cmd: "stow -S . --dir={{ ansible_env.HOME }}/Code/dotfiles/{{ item | basename }} --target={{ ansible_env.HOME}} --verbose=2"
  with_items: "{{ stow_pkgs }}"
  register: stow_result
  changed_when: "'LINK:' in stow_result.stdout"
