---
- name: Add APT signing keys
  become: true
  ansible.builtin.apt_key:
    url: "{{ item.key_url }}"
  loop: "{{ apt_repos }}"
- name: Add aditional repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
  loop: "{{ apt_repos }}"
- name: Update cache if the last update is more than one hour ago
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
- name: Install packages using Aptitude
  become: true
  ansible.builtin.apt:
    name: "{{ apt_installed_packages }}"
